language: php

php:
  - 7.2
  - 7.3

matrix:
  include:
  - name: "Mysql database test"
    services:
      - mysql
    addons:
      apt:
        sources:
          - mysql-5.7-trusty
        packages:
          - mysql-server
          - mysql-client
    env: DB_TYPE=mysql DB_HOST=127.0.0.1 DB_NAME=bobra_cpa DB_USER=root DB_PASS=
    before_script:
      - travis_retry composer self-update
      - travis_retry composer install --no-interaction --prefer-source
      - mysql -e 'CREATE DATABASE IF NOT EXISTS bobra_cpa;'
  - name: "Postgres database test"
    services:
      - postgresql
    addons:
      postgresql: "9.4"
    env: DB_TYPE=pgsql DB_HOST=localhost DB_NAME=bobra_cpa DB_USER=postgres DB_PASS=root
    before_script:
      - travis_retry composer self-update
      - travis_retry composer install --no-interaction --prefer-source
      - psql -c 'CREATE DATABASE bobra_cpa;' -U postgres

script:
    - ./vendor/bin/phpcs --standard=PSR2 ./src ./tests
    - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
